import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import './globals.css';
import Header from './sections/header';

const inter = Inter({
  variable: '--font-inter',
  subsets: ['latin'],
});

export const metadata: Metadata = {
  title: 'myxellia',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='en'>
      <body className={`${inter.variable} antialiased`}>
        <Header />
        <main className='w-full flex flex-col items-center'>{children}</main>
      </body>
    </html>
  );
}
